import streamlit as st
import os
from datetime import datetime
import quant_b_module
import quant_a_module

st.set_page_config(page_title="Project Finance - Group 12", layout="wide")

# --- Helper Function for Reports ---
def display_daily_report():
    """
    Function to display the daily report generated by the server.
    """
    st.subheader("Server Daily Report")
    
    # 1. Date selector (defaults to Today)
    selected_date = st.date_input("Today's report", datetime.now())
    
    # 2. Format date to match filename (YYYYMMDD)
    date_str = selected_date.strftime("%Y%m%d")
    
    # 3. Construct file path
    # IMPORTANT: Ensure your folder on the server is named 'reports' (plural).
    # If it is named 'report', change the line below to: f"report/daily_report_{date_str}.txt"
    file_path = f"reports/daily_report_{date_str}.txt" 
    
    # 4. Check if file exists and display it
    if os.path.exists(file_path):
        with open(file_path, "r") as f:
            report_content = f.read()
            st.code(report_content, language="text")
    else:
        st.info(f"No report found for {date_str}. (Reports are generated daily at 08:00 a.m).")

# Sidebar of Navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Menu", "Module Quant A (Mono-Actif)", "Module Quant B (Portfolio)"])

if page == "Menu":
    st.title("Project Python Git - Group 12")
    st.write("Welcome on our web platform for financial analysis.")
    st.write("Use the left menu to navigate")
    st.info("👈 Select a module from the sidebar.")
    st.divider()
    display_daily_report()

elif page == "Module Quant A (Mono-Actif)":
    quant_a_module.run_quant_a()

elif page == "Module Quant B (Portfolio)":
    quant_b_module.run_quant_b()
