# -*- coding: utf-8 -*-
"""Data Manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__2F3PDLMx5Z2gKCzsHBI1hCstkmc8yO
"""

import yfinance as yf
import logging

# Logging Configuration
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def get_data(tickers, period, interval="1d"):
    """
    Fetches historical market data for a list of tickers.
    Args:
        tickers (list): List of ticker symbols.
        period (str): Data period (e.g., '1y', '5d').
        interval (str): Data interval (e.g., '1d', '5m').
    Returns:
        pd.DataFrame: Adjusted Close prices.
    """
    try:
        # Download data
        df = yf.download(tickers, period=period, interval=interval, auto_adjust=True)

        # Handle different return formats from yfinance
        if 'Close' in df.columns:
            data = df['Close']
        else:
            data = df

        return data.dropna()
    except Exception as e:
        logger.error(f"Download error: {e}")
        return None