# -*- coding: utf-8 -*-
"""Portfolio Analytics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LS6qKlPPxf26SQMbo5N9roKoEh8nbyu-
"""

import numpy as np
import pandas as pd

def calculate_portfolio_performance(data, weights):
    """
    Calculates the portfolio's cumulative value and returns based on weights.
    """
    returns_df = data.pct_change().dropna()
    portfolio_returns = returns_df.dot(weights)

    # Base 100 Index
    portfolio_value = (1 + portfolio_returns).cumprod() * 100
    assets_value = (1 + returns_df).cumprod() * 100

    return portfolio_value, assets_value, returns_df

def calculate_metrics(series):
    """
    Calculates advanced risk and performance metrics.
    Includes: Total Return, Volatility, Sharpe, Sortino, Max Drawdown, Calmar, VaR, CVaR.
    """
    returns = series.pct_change().dropna()

    # 1. Basic Return Metrics
    total_return = (series.iloc[-1] / series.iloc[0]) - 1
    annualized_return = returns.mean() * 252

    # 2. Volatility (Annualized)
    volatility = returns.std() * np.sqrt(252)

    # 3. Downside Risk (Semi-Deviation) for Sortino
    negative_returns = returns[returns < 0]
    downside_deviation = negative_returns.std() * np.sqrt(252)

    # 4. Risk Free Rate (Assumed 2%)
    rf = 0.02

    # 5. Ratios
    sharpe = (annualized_return - rf) / volatility if volatility != 0 else 0
    sortino = (annualized_return - rf) / downside_deviation if downside_deviation != 0 else 0

    # 6. Drawdown
    cum_returns = (1 + returns).cumprod()
    running_max = cum_returns.cummax()
    drawdown = (cum_returns / running_max) - 1
    max_drawdown = drawdown.min()

    calmar = annualized_return / abs(max_drawdown) if max_drawdown != 0 else 0

    # 7. Value at Risk (VaR) - Historical 95%
    var_95 = returns.quantile(0.05)

    # 8. Conditional VaR (CVaR)
    cvar_95 = returns[returns <= var_95].mean()

    return {
        "Total Return": total_return,
        "Ann. Return": annualized_return,
        "Volatility": volatility,
        "Sharpe Ratio": sharpe,
        "Sortino Ratio": sortino,
        "Max Drawdown": max_drawdown,
        "Calmar Ratio": calmar,
        "VaR (95%)": var_95,
        "CVaR (95%)": cvar_95
    }