{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "87cf6abf-f99a-43ad-9414-9f7adbe64b5b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "import logging\n",
    "\n",
    "# Configuration logging\n",
    "logging.basicConfig(level=logging.INFO)\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "def get_data(tickers, period):\n",
    "    df = yf.download(tickers, period=period, auto_adjust=True)\n",
    "    if 'Close' in df.columns:\n",
    "        data = df['Close']\n",
    "    else:\n",
    "        data = df\n",
    "    \n",
    "    data = data.dropna()\n",
    "    return data\n",
    "\n",
    "def calculate_metrics(series):\n",
    "    returns = series.pct_change().dropna()\n",
    "    \n",
    "    # return total\n",
    "    total_return = (series.iloc[-1] / series.iloc[0]) - 1\n",
    "    \n",
    "    # annual vol\n",
    "    volatility = returns.std() * np.sqrt(252)\n",
    "    \n",
    "    # Sharpe Ratio \n",
    "    risk_free_rate = 0.02\n",
    "    annualized_return = returns.mean() * 252\n",
    "    if volatility!=0 :\n",
    "        sharpe = (annualized_return - risk_free_rate) / volatility\n",
    "    else :\n",
    "        sharpe=0\n",
    "    \n",
    "    # Max Drawdown\n",
    "    cum_returns = (1 + returns).cumprod()\n",
    "    running_max = cum_returns.cummax()\n",
    "    drawdown = (cum_returns / running_max) - 1\n",
    "    max_drawdown = drawdown.min()\n",
    "    \n",
    "    return {\n",
    "        \"Rendement Total\": total_return,\n",
    "        \"Volatilité\": volatility,\n",
    "        \"Sharpe\": sharpe,\n",
    "        \"Max Drawdown\": max_drawdown\n",
    "    }\n",
    "\n",
    "def run_quant_b():\n",
    "    st.markdown(\"\"\"\n",
    "    <style>\n",
    "        .metric-card { background-color: #f0f2f6; padding: 10px; border-radius: 5px; border-left: 5px solid #ff4b4b; }\n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "    st.header(\" Multi-Asset Portfolio Manager \")\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # SIDEBAR CONFIGURATION \n",
    "    st.sidebar.header(\"1. Univers d'Investissement\")\n",
    "    \n",
    "    default_tickers = \"AAPL, MSFT, GOOGL, AMZN, TSLA\"\n",
    "    tickers_input = st.sidebar.text_input(\"Tickers (séparés par virgules)\", default_tickers)\n",
    "    tickers = [x.strip().upper() for x in tickers_input.split(',') if x.strip() != '']\n",
    "    \n",
    "    period = st.sidebar.selectbox(\"Période\", [\"3mo\", \"6mo\", \"1y\", \"2y\", \"5y\", \"max\"], index=2)\n",
    "\n",
    "    # Data recuperation\n",
    "    if len(tickers) < 3:\n",
    "        st.error(\"Project ask for at least 3 assets\")\n",
    "        return\n",
    "\n",
    "    with st.spinner(\"Recuperation data\"):\n",
    "        data = get_data(tickers, period)\n",
    "\n",
    "    if data is None or data.empty:\n",
    "        st.error(\"Error check the tickers\")\n",
    "        return\n",
    "\n",
    "    #making sure we didn't missed a ticker\n",
    "    available_tickers = data.columns.tolist()\n",
    "    missing = set(tickers) - set(available_tickers)\n",
    "    if missing:\n",
    "        st.warning(f\"Données introuvables pour : {', '.join(missing)}\")\n",
    "    \n",
    "    st.sidebar.header(\"Allocation\")\n",
    "    st.sidebar.write(\"Weighting of the portfolio :\")\n",
    "    \n",
    "    weights_input = []\n",
    "    for t in available_tickers:\n",
    "        w = st.sidebar.slider(f\"{t}\", 0.0, 1.0, 1.0/len(available_tickers), 0.05, key=t)\n",
    "        weights_input.append(w)\n",
    "    \n",
    "    total_w = sum(weights_input)\n",
    "    if total_w == 0:\n",
    "        weights = np.array([1/len(available_tickers)] * len(available_tickers))\n",
    "    else:\n",
    "        weights = np.array([w/total_w for w in weights_input])\n",
    "    \n",
    "    st.sidebar.markdown(\"---\")\n",
    "    st.sidebar.info(f\"**Poids effectifs :** {np.round(weights*100, 1)}%\")\n",
    "\n",
    "    # Calculations\n",
    "    # daily returns\n",
    "    returns_df = data.pct_change().dropna()\n",
    "    \n",
    "    # Return of the portfolio\n",
    "    # R_p = w1*R1 + w2*R2 ...\n",
    "    portfolio_returns = returns_df.dot(weights)\n",
    "    \n",
    "    portfolio_value = (1 + portfolio_returns).cumprod() * 100\n",
    "    assets_value = (1 + returns_df).cumprod() * 100\n",
    "    \n",
    "    chart_data = assets_value.copy()\n",
    "    chart_data['PORTFOLIO'] = portfolio_value\n",
    "\n",
    "    # Display Dashboard\n",
    "    \n",
    "    # Performance return\n",
    "    st.subheader(\"📈 Comparaison Actifs vs Portefeuille (Base 100)\")\n",
    "    \n",
    "    fig_perf = go.Figure()\n",
    "    \n",
    "    for col in assets_value.columns:\n",
    "        fig_perf.add_trace(go.Scatter(x=assets_value.index, y=assets_value[col], \n",
    "                                      name=col, line=dict(width=1, dash='dot'), opacity=0.7))\n",
    "    \n",
    "    fig_perf.add_trace(go.Scatter(x=portfolio_value.index, y=portfolio_value, \n",
    "                                  name='PORTFOLIO', line=dict(color='blue', width=4)))\n",
    "    \n",
    "    fig_perf.update_layout(hovermode=\"x unified\", template=\"plotly_white\")\n",
    "    st.plotly_chart(fig_perf, use_container_width=True)\n",
    "\n",
    "    # Metrics\n",
    "    st.subheader(\"Performance & Risk\")\n",
    "    \n",
    "    # Computation of metrics\n",
    "    port_metrics = calculate_metrics(portfolio_value)\n",
    "    \n",
    "    col1, col2, col3, col4 = st.columns(4)\n",
    "    col1.metric(\"Rendement Total\", f\"{port_metrics['Rendement Total']*100:.2f} %\")\n",
    "    col2.metric(\"Volatilité (Annu.)\", f\"{port_metrics['Volatilité']*100:.2f} %\")\n",
    "    col3.metric(\"Sharpe Ratio\", f\"{port_metrics['Sharpe']:.2f}\")\n",
    "    col4.metric(\"Max Drawdown\", f\"{port_metrics['Max Drawdown']*100:.2f} %\")\n",
    "\n",
    "    # C. Effet de Diversification (Spécifique Quant B)\n",
    "    st.markdown(\"---\")\n",
    "    c1, c2 = st.columns([1, 1])\n",
    "    \n",
    "    with c1:\n",
    "        st.subheader(\"🔗 Matrice de Corrélation\")\n",
    "        corr_matrix = returns_df.corr()\n",
    "        fig_corr = px.imshow(corr_matrix, text_auto=True, color_continuous_scale='RdBu_r', zmin=-1, zmax=1)\n",
    "        st.plotly_chart(fig_corr, use_container_width=True)\n",
    "        \n",
    "    with c2:\n",
    "        st.subheader(\"🛡️ Effet de Diversification\")\n",
    "        # Calcul : Moyenne pondérée des volatilités individuelles vs Volatilité réelle du portefeuille\n",
    "        # Si Vol_Portefeuille < Moyenne_Pondérée_Vol, c'est qu'il y a diversification\n",
    "        \n",
    "        asset_vols = returns_df.std() * np.sqrt(252)\n",
    "        weighted_avg_vol = np.dot(weights, asset_vols)\n",
    "        actual_vol = port_metrics['Volatilité']\n",
    "        \n",
    "        diversification_benefit = weighted_avg_vol - actual_vol\n",
    "        div_pct = (diversification_benefit / weighted_avg_vol) * 100\n",
    "        \n",
    "        st.write(f\"Volatilité Moyenne Pondérée : **{weighted_avg_vol*100:.2f}%**\")\n",
    "        st.write(f\"Volatilité Réelle Portefeuille : **{actual_vol*100:.2f}%**\")\n",
    "        \n",
    "        st.success(f\"📉 Gain de Diversification : **-{div_pct:.2f}%** de risque éliminé grâce aux corrélations imparfaites.\")\n",
    "        \n",
    "        # Graphique Risk/Return (Scatter Plot)\n",
    "        # On crée un petit DataFrame pour le plot\n",
    "        risk_ret_data = pd.DataFrame({\n",
    "            'Volatilité': asset_vols,\n",
    "            'Rendement': returns_df.mean() * 252,\n",
    "            'Type': ['Actif'] * len(asset_vols),\n",
    "            'Ticker': asset_vols.index\n",
    "        })\n",
    "        \n",
    "        # Ajout du portefeuille\n",
    "        risk_ret_data.loc['PORTFOLIO'] = [actual_vol, returns_df.mean().dot(weights) * 252, 'Portefeuille', 'PORTFOLIO']\n",
    "        \n",
    "        fig_scatter = px.scatter(risk_ret_data, x='Volatilité', y='Rendement', color='Type', \n",
    "                                 text='Ticker', size=[1]*len(risk_ret_data), size_max=10,\n",
    "                                 title=\"Carte Risque / Rendement\", color_discrete_map={'Portefeuille': 'blue', 'Actif': 'gray'})\n",
    "        fig_scatter.update_traces(textposition='top center')\n",
    "        st.plotly_chart(fig_scatter, use_container_width=True)\n",
    "\n",
    "    # D. Données\n",
    "    with st.expander(\"Voir les données brutes\"):\n",
    "        st.dataframe(data.tail())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
